name: prototip_tfg
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: "^0.5.0+1"
  provider: ^4.0.5
  intl: ^0.16.0
  http: ^0.12.1
  flutter_calendar_carousel: ^1.4.12
  intl_phone_number_input: ^0.4.5
  cloud_firestore: "^0.14.1+3"
  cupertino_icons: ^0.1.2
  firebase_auth: "^0.18.1+2"
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_native_splash:
  image: assets/images/splashscreen.png
  color: "42a5f5"
  fill: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
